name: ChatResponderMC
version: ${version}
main: com.alfie51m.ChatResponderMC.ChatResponder
api-version: '1.21'
softdepend: [PlaceholderAPI]

commands:
  chatresponder:
    description: Reloads the ChatResponderMC configuration.
    usage: /chatresponder reload
    permission: chatresponder.reload
permissions:
  chatresponder.reload:
    description: Allows player to reload the plugin configuration.
    default: op